apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
	- postgres-config.yaml
	- postgres-deployment.yaml
	- postgres-service.yaml
	- postgres-persistent-volume.yaml
	- postgres-persistent-volume-claim.yaml