apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: recipe-service-deployment
  template:
    metadata:
      labels:
        app: recipe-service-deployment
    spec:
      containers:
      - name: app
        image: waidmann/recipe-service:0.0.3
        env:
        - name: DATABASE_HOST
          value: "postgres.default.svc.cluster.local"
        - name: DATABASE_USERNAME
          value: "admin"
        - name: DATABASE_PASSWORD
          value: "psltest"
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP