apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: recipe-service-deployment
  template:
    metadata:
      labels:
        app: recipe-service-deployment
    spec:
      containers:
      - name: app
        image: recipe-service:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP